version = 4.2.0
archive_dir = /etc/letsencrypt/archive/abexacloud.com
cert = /etc/letsencrypt/live/abexacloud.com/cert.pem
privkey = /etc/letsencrypt/live/abexacloud.com/privkey.pem
chain = /etc/letsencrypt/live/abexacloud.com/chain.pem
fullchain = /etc/letsencrypt/live/abexacloud.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 86ffe5214160516c38ebd421e9b2de58
key_type = rsa
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
