version: "3.8"

services:
  db:
    image: postgres:13
    container_name: hmdm_db
    restart: always
    environment:
      POSTGRES_DB: hmdm
      POSTGRES_USER: hmdm
      POSTGRES_PASSWORD: hmdm
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data

  hmdm:
    # image: headwindmdm/hmdm:0.1.5
    image: hmdm:latest
    container_name: hmdm_app
    restart: always
    depends_on:
      - db
    ports:
      - "443:8443"        # HTTPS
      - "31000:31000"     # Puerto de comunicación con dispositivos
    environment:
      SQL_HOST: db        # usamos el nombre del servicio en vez de la IP
      SQL_BASE: hmdm
      SQL_USER: hmdm
      SQL_PASS: hmdm
      BASE_DOMAIN: abexacloud.com
    volumes:
      # Frontend estático
#      - ../server/src/main/webapp/app:/usr/local/tomcat/webapps/ROOT/app:cached
#      - ../server/src/main/webapp/css:/usr/local/tomcat/webapps/ROOT/css:cached
#      - ../server/src/main/webapp/images:/usr/local/tomcat/webapps/ROOT/images:cached
#      - ../server/src/main/webapp/localization:/usr/local/tomcat/webapps/ROOT/localization:cached
#      - ../server/src/main/webapp/index.html:/usr/local/tomcat/webapps/ROOT/index.html:cached
#      - ../server/src/main/webapp/test.html:/usr/local/tomcat/webapps/ROOT/test.html:cached
#      - ../server/src/main/webapp/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt:cached
#      # AGREGAR ESTOS:
#      - ../server/src/main/webapp/lib:/usr/local/tomcat/webapps/ROOT/lib:cached
#      - ../server/src/main/webapp/ext:/usr/local/tomcat/webapps/ROOT/ext:cached
#      # Configuración de Tomcat (IMPORTANTE)
##      - ./context.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml:ro

      #      - ../server/src/main/webapp:/usr/local/tomcat/webapps/ROOT:consistent
      - ./certs/letsencrypt/live/abexacloud.com:/etc/letsencrypt/live/abexacloud.com:ro
      - ./volumes/work:/usr/local/tomcat/work

volumes:
  db_data:
